export { default as two } from "./two";
export { default as three } from "./three";
export { default as four } from "./four";
export { default as five } from "./five";
export { default as six } from "./six";
export { default as seven } from "./seven";
export { default as nine } from "./nine";
export { default as ten } from "./ten";
export { default as twelve } from "./twelve";
